### ISSUE TITLE
Contribute back?

### ISSUE THREAD

**Issue by kirb** [w0lfschild/whosTyping#1]
What did you change here? Hard to tell since there’s no git history. Could you PR these back so I can make an official update?

If you plan to release this, please change the name.

**Comment by w0lfschild** [comment]
Well here's the changes:

- It's made with Xcode and ZKSwizzle instead of Theos
- It uses different hooks to determine when someone is typing (`IMTypingChatItem` and `SOTypingIndicatorView`)
- It works on Messages 11.0 on macOS 10.13 but I haven't tested anything below that
- It doesn't support Read indicators right now
- It doesn't show a first run alert or check for updates
- It has the option to show an animated statusbar Icon
- It uses SIMBL

I can make a fork of the old project.

**Comment by kirb** [comment]
Does look cleaner actually. I mostly copied hooks/logic from the [iOS tweak](https://github.com/hbang/TypeStatus/blob/master/relay/IMAgentRelay.x) which injects into imagent to get the notifications, hence why I use IMCore/IMFoundation classes here. The ugly -[FZMessage setTimeRead:] hook changed to a far more reliable IMDServiceSession hook long long ago, really makes me realise how long it’s been since I worked on this 😕

I’d prefer to leave the build system as Theos, partly so I can use Logos. Animated indicator would be cool to have.

I think it’d be easier if I copy over some interesting bits from you, if you can give me permission to use it under the Apache license.

**Comment by w0lfschild** [comment]
You can copy whatever you want from this repo.
